# Generated by Django 2.2.1 on 2019-06-05 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Expression",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("expression", models.TextField()),
                ("result", models.IntegerField()),
            ],
        )
    ]
