# Generated by Django 2.2.1 on 2019-06-06 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expressions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expression',
            name='expression',
            field=models.CharField(max_length=255),
        ),
    ]
