# Generated by Django 2.2.1 on 2019-06-01 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expressions', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='expressions',
            old_name='expression',
            new_name='expressions',
        ),
    ]
