# Generated by Django 2.2.1 on 2019-06-01 16:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expressions', '0002_auto_20190601_1444'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Expressions',
            new_name='Expression',
        ),
        migrations.RenameField(
            model_name='expression',
            old_name='expressions',
            new_name='expression',
        ),
    ]
