# Generated by Django 2.2.1 on 2019-06-06 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expressions', '0003_auto_20190606_1541'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expression',
            name='expression',
            field=models.TextField(),
        ),
    ]
